DROP DATABASE TEST;
DELETE FROM mysql.user WHERE User='' AND Host = '%';
DELETE FROM mysql.db WHERE User='' AND Host = '%';
DELETE FROM mysql.tables_priv WHERE User='' AND Host = '%';
DELETE FROM mysql.columns_priv WHERE User='' AND Host = '%';
DELETE FROM mysql.user WHERE User='' AND Host = 'localhost';
DELETE FROM mysql.db WHERE User='' AND Host = 'localhost';
DELETE FROM mysql.tables_priv WHERE User='' AND Host = 'localhost';
DELETE FROM mysql.columns_priv WHERE User='' AND Host = 'localhost';
DELETE FROM mysql.user WHERE User='root' AND Host = '%';
DELETE FROM mysql.db WHERE User='root' AND Host = '%';
DELETE FROM mysql.tables_priv WHERE User='root' AND Host = '%';
DELETE FROM mysql.columns_priv WHERE User='root' AND Host = '%';
REVOKE ALL PRIVILEGES ON *.* FROM 'root'@'localhost';
REVOKE GRANT OPTION ON *.* FROM 'root'@'localhost';
DELETE FROM mysql.db WHERE User='root' AND Host = 'localhost';
DELETE FROM mysql.tables_priv WHERE User='root' AND Host = 'localhost';
DELETE FROM mysql.columns_priv WHERE User='root' AND Host = 'localhost';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
UPDATE mysql.user SET password='5c1fb21a20d15f82' WHERE User = 'root';