CREATE TABLE funcionario (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  situ BOOL NOT NULL,
  recvale BOOL NOT NULL,
  limite FLOAT(6,2) NOT NULL,
  senha VARCHAR(32) NOT NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE fornecedor (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  razao VARCHAR(60) NOT NULL,
  cnpj VARCHAR(18) NOT NULL,
  ie VARCHAR(13) NOT NULL,
  fone VARCHAR(14) NOT NULL,
  contato VARCHAR(20) NOT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE mesa (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  mesa VARCHAR(4) NOT NULL,
  dataAbe DATE NULL,
  horaAbe TIME NULL,
  fid INTEGER UNSIGNED NOT NULL,
  dataFec DATE NULL,
  horaFec TIME NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE produto (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(50) NOT NULL,
  preco FLOAT(6,2) NOT NULL,
  tipo BOOL NOT NULL,
  divpessoa BOOL NOT NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE periodo (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  dataIni DATE NULL,
  dataFin DATE NULL,
  horaIni TIME NULL,
  horaFin TIME NULL,
  situ INT(1) NOT NULL,
  dataAbe DATE NULL,
  dataFec DATE NULL,
  horaAbe TIME NULL,
  horaFec TIME NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE cliente (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  fone VARCHAR(14) NOT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE auditoria (
  id INTEGER UNSIGNED NOT NULL,
  usuario INTEGER UNSIGNED NOT NULL,
  date DATE NULL,
  hora TIME NULL,
  comando VARCHAR(7) NOT NULL,
  valores TEXT NOT NULL,
  tabela VARCHAR(20) NOT NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE usuario (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  login VARCHAR(32) NOT NULL,
  senha VARCHAR(32) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  nivel INT(1) NOT NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE config (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  campo VARCHAR(40) NOT NULL,
  valor VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)
TYPE=InnoDB;

CREATE TABLE vale (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  fid INTEGER UNSIGNED NOT NULL,
  emissao DATE NULL,
  historico TEXT NOT NULL,
  valor FLOAT(6,2) NOT NULL,
  turno INT(1) NOT NULL,
  PRIMARY KEY(id),
  INDEX vale_funcionario(fid),
  FOREIGN KEY(fid)
    REFERENCES funcionario(id)
      ON DELETE RESTRICT
      ON UPDATE NO ACTION
)
TYPE=InnoDB;

CREATE TABLE promocao (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  pid INTEGER UNSIGNED NOT NULL,
  dia INT(1) NOT NULL,
  preco FLOAT(6,2) NOT NULL,
  PRIMARY KEY(id),
  INDEX promocao_produto(pid),
  FOREIGN KEY(pid)
    REFERENCES produto(id)
      ON DELETE CASCADE
      ON UPDATE NO ACTION
)
TYPE=InnoDB;

CREATE TABLE bonificacao (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  fid INTEGER UNSIGNED NOT NULL,
  emissao DATE NULL,
  historico TEXT NOT NULL,
  valor FLOAT(6,2) NOT NULL,
  turno INT(1) NOT NULL,
  PRIMARY KEY(id),
  INDEX bonificacao_funcionario(fid),
  FOREIGN KEY(fid)
    REFERENCES funcionario(id)
      ON DELETE RESTRICT
      ON UPDATE NO ACTION
)
TYPE=InnoDB;

CREATE TABLE devfornec (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  fid INTEGER UNSIGNED NOT NULL,
  emissao DATE NULL,
  historico TEXT NOT NULL,
  valor FLOAT(6,2) NOT NULL,
  turno INT(1) NOT NULL,
  PRIMARY KEY(id),
  INDEX devfornec_fornecedor(fid),
  FOREIGN KEY(fid)
    REFERENCES fornecedor(id)
      ON DELETE RESTRICT
      ON UPDATE NO ACTION
)
TYPE=InnoDB;

CREATE TABLE mesaItem (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  mid INTEGER UNSIGNED NOT NULL,
  pid INTEGER UNSIGNED NOT NULL,
  qtde INTEGER UNSIGNED NOT NULL,
  preco FLOAT(6,2) NOT NULL,
  PRIMARY KEY(id),
  INDEX mesaItem_mesa(mid),
  FOREIGN KEY(mid)
    REFERENCES mesa(id)
      ON DELETE CASCADE
      ON UPDATE NO ACTION
)
TYPE=InnoDB;

CREATE TABLE venda (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  fid INTEGER UNSIGNED NOT NULL,
  cid INTEGER UNSIGNED NOT NULL,
  dataVen DATE NULL,
  taxa INT(2) NOT NULL,
  mesa VARCHAR(4) NOT NULL,
  dinheiro FLOAT(6,2) NOT NULL,
  cheque FLOAT(6,2) NOT NULL,
  cartao FLOAT(6,2) NOT NULL,
  ticket FLOAT(6,2) NOT NULL,
  desconto FLOAT(6,2) NOT NULL,
  PRIMARY KEY(id),
  INDEX venda_funcionario(fid),
  INDEX venda_cliente(cid),
  FOREIGN KEY(fid)
    REFERENCES funcionario(id)
      ON DELETE RESTRICT
      ON UPDATE NO ACTION,
  FOREIGN KEY(cid)
    REFERENCES cliente(id)
      ON DELETE RESTRICT
      ON UPDATE NO ACTION
)
TYPE=InnoDB;

CREATE TABLE valeItem (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  pid INTEGER UNSIGNED NOT NULL,
  vid INTEGER UNSIGNED NOT NULL,
  vPro FLOAT(6,2) NOT NULL,
  PRIMARY KEY(id),
  INDEX valeItem_produto(pid),
  INDEX valeItem_vale(vid),
  FOREIGN KEY(pid)
    REFERENCES produto(id)
      ON DELETE RESTRICT
      ON UPDATE NO ACTION,
  FOREIGN KEY(vid)
    REFERENCES vale(id)
      ON DELETE CASCADE
      ON UPDATE NO ACTION
)
TYPE=InnoDB;

CREATE TABLE vendaItem (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  pid INTEGER UNSIGNED NOT NULL,
  vid INTEGER UNSIGNED NOT NULL,
  qtde INT(3) NOT NULL,
  preco FLOAT(6,2) NOT NULL,
  PRIMARY KEY(id),
  INDEX vendaItem_venda(vid),
  INDEX vendaItem_produto(pid),
  FOREIGN KEY(vid)
    REFERENCES venda(id)
      ON DELETE CASCADE
      ON UPDATE NO ACTION,
  FOREIGN KEY(pid)
    REFERENCES produto(id)
      ON DELETE RESTRICT
      ON UPDATE NO ACTION
)
TYPE=InnoDB;


